# docker-compose.yml
version: "3"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: hexletbasics/services-app
    command: bash -c 'sleep 3 && make ci-check'
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
