---
version: "3"

 webserver:
    image: caddy:2.6
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./public:/etc/caddy/public"
      - caddy_data:/data
      - caddy_config:/config
    # depends_on:
    #   - web

volumes:
  redis:
  caddy_data:
  caddy_config:
  app_tmp:
  global_tmp:
